[package]
name = "thoth-export-server"
version = "0.8.2"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Actix instance serving Thoth's metadata export endpoints"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[dependencies]
thoth-api = { version = "0.8.2", path = "../thoth-api" }
thoth-errors = { version = "0.8.2", path = "../thoth-errors" }
thoth-client = { version = "0.8.2", path = "../thoth-client" }
actix-web = "4.0.1"
actix-cors = "0.6.0"
chrono = { version = "0.4", features = ["serde"] }
csv = "1.1.6"
env_logger = "0.7.1"
lazy_static = "1.4.0"
log = "0.4.14"
paperclip = { version = "0.7.0", features = ["uuid"] }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.7", features = ["serde"] }
xml-rs = "0.8.0"
