[package]
name = "thoth-export-server"
version = "0.3.6"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Actix instance serving Thoth's metadata export endpoints"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[dependencies]
thoth-api = { version = "0.3.6", path = "../thoth-api" }
thoth-client = { version = "0.3.6", path = "../thoth-client" }
actix-rt = "1.0.0"
actix-web = "3.0.0"
actix-cors = "0.4.1"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.7.1"
log = "0.4.14"
serde_json = "1.0"
uuid = { version = "0.7", features = ["serde"] }
xml-rs = "0.8.0"
