[package]
name = "thoth"
version = "0.1.0"
authors = ["Javier Arias <javier@arias.re>"]
edition = "2018"

[dependencies]
actix-http = "1.0.1"
actix-web = "2.0.0"
actix-rt = "1.0.0"
chrono = "0.4"
diesel = { version = "1.4.0", features = ["postgres", "uuidv07", "chrono", "r2d2"] }
diesel-derive-enum = { version = "0.4", features = ["postgres"] }
dotenv = "0.9.0"
env_logger = "0.6.2"
failure = "0.1.6"
futures = "0.1"
juniper = "0.14.2"
phf = { version = "0.8", features = ["macros"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = "0.7"
