# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
import_types = [
  "diesel::sql_types::*",
  "crate::model::contribution::Contribution_type",
  "crate::model::work::Work_type",
  "crate::model::work::Work_status",
  "crate::model::publication::Publication_type",
  "crate::model::language::Language_relation",
  "crate::model::language::Language_code",
  "crate::model::series::Series_type",
  "crate::model::price::Currency_code",
  "crate::model::subject::Subject_type"
]
