version: "3.5"

services:
  db:
    image: postgres:12
    container_name: "thoth_db"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

  api:
    image: openbookpublishers/thoth
    container_name: "thoth_api"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db

  gui:
    image: openbookpublishers/thoth
    container_name: "thoth_gui"
    restart: unless-stopped
    command: ["/thoth", "start", "gui"]
    env_file:
      - .env
    depends_on:
      - api

volumes:
  db:
