name: build-and-test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  THOTH_API: https://api.thoth.openbookpublishers.com

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.19.0'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install rollup
      run: sudo npm install -g rollup@2.28.2
    - name: Install WASM pack
      run: cargo install wasm-pack
    - name: Compile WASM
      run: wasm-pack build thoth-app/ --target web --release
    - name: Pack APP
      run: rollup thoth-app/main.js --format iife --file thoth-app/pkg/thoth_app.js
    - name: Build binary
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
    - name: Run linting
      run: cargo clippy --all --all-targets --all-features -- -D warnings
    - name: Check style
      run: cargo fmt --all -- --check
