[package]
name = "thoth-api"
version = "0.2.0"
authors = ["Javier Arias <javi@openbookpublishers.com>"]
edition = "2018"
license = "Apache-2.0"
description = "GraphQL API for bibliographic data"
repository = "https://github.com/openbookpublishers/thoth"
readme = "README.md"

[badges]
travis-ci = { repository = "openbookpublishers/thoth" }
maintenance = { status = "actively-developed" }

[features]
backend = ["diesel", "diesel-derive-enum", "diesel_migrations"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4.0", features = ["postgres", "uuidv07", "chrono", "r2d2"], optional = true }
diesel-derive-enum = { version = "1.1.0", features = ["postgres"], optional = true }
diesel_migrations = { version = "1.4.0", features = ["postgres"], optional = true }
dotenv = "0.9.0"
failure = "0.1.6"
juniper = "0.14.2"
phf = { version = "0.8", features = ["macros"] }
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0.115", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.7", features = ["serde"] }
xml-rs = "0.8.0"

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = ["prepush-hook", "run-cargo-check", "run-cargo-test", "run-cargo-clippy", "run-cargo-fmt"] }
