[package]
name = "thoth-client"
version = "0.4.1"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2018"
license = "Apache-2.0"
description = "GraphQL Client for bibliographic data"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[dependencies]
thoth-api = {version = "0.4.1", path = "../thoth-api" }
thoth-errors = {version = "0.4.1", path = "../thoth-errors" }
graphql_client = "0.9.0"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.10", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
uuid = { version = "0.7", features = ["serde"] }
