[package]
name = "thoth-client"
version = "0.9.12"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2018"
license = "Apache-2.0"
description = "GraphQL Client for bibliographic data"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[dependencies]
thoth-api = {version = "0.9.12", path = "../thoth-api" }
thoth-errors = {version = "0.9.12", path = "../thoth-errors" }
graphql_client = "0.12.0"
chrono = { version = "0.4.23", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
uuid = { version = "0.8.2", features = ["serde"] }
