[package]
name = "thoth-api-server"
version = "0.3.5"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Actix instance serving Thoth's GraphQL endpoints"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[dependencies]
thoth-api = { version = "0.3.5", path = "../thoth-api", features = ["backend"] }
thoth-client = { version = "0.3.5", path = "../thoth-client" }
actix-rt = "1.0.0"
actix-web = "3.0.0"
actix-cors = "0.4.1"
actix-identity = "0.3.1"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.7.1"
juniper = "0.14.2"
serde_json = "1.0"
uuid = { version = "0.7", features = ["serde"] }
xml-rs = "0.8.0"
