[package]
name = "thoth-app-server"
version = "0.3.6"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Actix instance serving Thoth's WASM GUI statically"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[dependencies]
actix-rt = "1.0.0"
actix-web = "3.0.0"
actix-cors = "0.5.4"
env_logger ="0.7.1"
