[package]
name = "thoth-app-server"
version = "0.8.8"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Actix instance serving Thoth's WASM GUI statically"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[dependencies]
actix-web = "4.0.1"
actix-cors = "0.6.0"
env_logger ="0.7.1"
