name: build-test-and-check

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.rs'
      - '**.js'
      - '**.json'
      - '**.html'
      - 'Cargo.lock'
      - '**Cargo.toml'
      - 'diesel.toml'
  pull_request:
    paths-ignore:
      - '**.rs'
      - '**.js'
      - '**.json'
      - '**.html'
      - 'Cargo.lock'
      - '**Cargo.toml'
      - 'diesel.toml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
  format_check:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
