name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  THOTH_GRAPHQL_API: https://api.thoth.pub
  THOTH_EXPORT_API: https://export.thoth.pub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.19.0'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'v0.9.1'
    - name: Install rollup
      run: sudo npm install -g rollup@2.28.2
    - name: Compile WASM
      run: wasm-pack build thoth-app/ --target web --release
    - name: Pack APP
      run: rollup thoth-app/main.js --format iife --file thoth-app/pkg/thoth_app.js
    - name: Build binary
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose
