name: build-dev-docker-image

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'Dockerfile.dev'
  pull_request:
    paths:
      - 'Dockerfile.dev'
  workflow_dispatch:

jobs:
  build_dev_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: openbookpublishers/thoth:latest
          file: Dockerfile.dev
          build-args: |
            THOTH_GRAPHQL_API=https://api.thoth.pub
            THOTH_EXPORT_API=https://export.thoth.pub
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
