name: build-dev-docker-image

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - 'Dockerfile.dev'
  pull_request:
    paths-ignore:
      - 'Dockerfile.dev'

jobs:
  build_dev_docker_image:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
