name: publish-to-dockerhub

on:
  release:
    types: [published]

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: openbookpublishers/thoth:latest
          build-args: |
            THOTH_GRAPHQL_API=https://api.thoth.pub
            THOTH_EXPORT_API=https://export.thoth.pub
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
