name: build-docker-image

on:
  push:
    branches:
      - 'release/**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: openbookpublishers/thoth:latest
          build-args: |
            THOTH_API=https://api.thoth.pub
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
